
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/pets_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/auth/realms/pets-api-realm
  kafka:
    bootstrapServers: kafka:9092
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
      kafka:
        binder:
          autoCreateTopics: true
          producerProperties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://schemaregistry:8085
      defaultBinder: kafka
      source: petResourceRequest
      binder:
        brokers: kafka:9092
      bindings:
        petResourceRequest-out-0:
          destination: dev.donation.pet-resource-request
          content-type: application/*+avro

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      clientId: pets-client
      clientSecret: 371ff349-a1d7-4fa6-8bf4-4294b3f97176
      usePkceWithAuthorizationCodeGrant: true
  api-docs:
    path: /api-docs
  oAuthFlow:
    authorizationUrl: http://keycloak:8180/auth/realms/pets-api-realm/protocol/openid-connect/auth
    tokenUrl: http://keycloak:8180/auth/realms/pets-api-realm/protocol/openid-connect/token
