
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pets_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      username: root
      password: password
      database: shelter
      host: localhost
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/pets-api-realm
  redis:
    host: localhost
    port: 6379


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      clientId: pets-client
      clientSecret: 371ff349-a1d7-4fa6-8bf4-4294b3f97176
      usePkceWithAuthorizationCodeGrant: true
  api-docs:
    path: /api-docs
  oAuthFlow:
    authorizationUrl: http://localhost:8180/auth/realms/pets-api-realm/protocol/openid-connect/auth
    tokenUrl: http://localhost:8180/auth/realms/pets-api-realm/protocol/openid-connect/token
