

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pets_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs